import Tests.CounterSpec
import Tests.PairSpec
import Tests.FlagSpec
import Tests.WindowSpec
import Tests.PhaseSpec
import Tests.ChoiceSpec
import Tests.ClockSpec
import Tests.TransferSpec
import Tests.Fixtures
import Tests.ProfileSpec
import Tests.ExtractSpec
import Tests.EmitSpec
import Tests.BuildSpec
import Tests.LayoutSpec
import Tests.Sha256Spec
import Tests.EvmSpec
import Tests.EvmBuildSpec
import Tests.DumpIncrement
