import Tests.CounterSpec
import Tests.PairSpec
import Tests.FlagSpec
import Tests.WindowSpec
import Tests.BookSpec
import Tests.PhaseSpec
import Tests.ChoiceSpec
import Tests.ClockSpec
import Tests.TransferSpec
import Tests.PingSpec
import Tests.CallSpec
import Tests.InfoSpec
import Tests.PeerSpec
import Tests.PdaSpec
import Tests.SignedSpec
import Tests.CreateSpec
import Tests.TokenXferSpec
import Tests.Token2022Spec
import Tests.AtaSpec
import Tests.RentSpec
import Tests.TokenMintSpec
import Tests.SysAllocSpec
import Tests.TokenAccSpec
import Tests.MemoSpec
import Tests.CreatePdaSpec
import Tests.TokenApproveSpec
import Tests.TokenFreezeSpec
import Tests.TokenAuthSpec
import Tests.EpochSpec
import Tests.TokenSizeSpec
import Tests.SysSeedSpec
import Tests.SysXferSpec
import Tests.TokenMint2Spec
import Tests.TokenNativeSpec
import Tests.HashSpec
import Tests.KeysSpec
import Tests.KeccakSpec
import Tests.TrioSpec
import Tests.GateSpec
import Tests.NonceSpec
import Tests.TokenOwnerSpec
import Tests.TokenMsSpec
import Tests.SelfLogSpec
import Tests.PhoenixSpec
import Tests.PhoenixV1ProfileSpec
import Tests.CliSpec
import Tests.Fixtures
import Tests.ProfileSpec
import Tests.ExtractSpec
import Tests.EmitSpec
import Tests.BuildSpec
import Tests.LayoutSpec
import Tests.Sha256Spec
import Tests.EvmSpec
import Tests.EvmSdkSpec
import Tests.EvmCallResultSpec
import Tests.EvmPrecompileSpec
import Tests.EvmLogErrorSpec
import Tests.EvmPayableSpec
import Tests.EvmEnvironmentSpec
import Tests.CoreCodecSpec
import Tests.CoreCollectionsSpec
import Tests.CrossTargetCodecSpec
import Tests.EvmBuildSpec
import Tests.EvmCtxSpec
import Tests.EvmBoundedSpec
import Tests.EvmStaticStorageSpec
import Tests.EvmOrderedStorageSpec
import Tests.EvmEffectStateSpec
import Tests.EvmReentrancySpec
import Tests.EvmErc721Spec
import Tests.EvmErc1155Spec
import Tests.EvmRolesSpec
import Tests.EvmStorageVecSpec
import Tests.EvmBitmapSpec
import Tests.EvmStorageRingSpec
import Tests.EvmStorageEnumerableSetSpec
import Tests.EvmStorageEnumerableMapSpec
import Tests.EvmStorageCheckpointsSpec
import Tests.EvmSafeCastSpec
import Tests.EvmPausableSpec
import Tests.TipJarSpec
import Tests.LangSpec
import Tests.VaultSpec
import Tests.OwnableSpec
import Tests.TokenSpec
import Tests.CappedSpec
import Tests.AccessSdkSpec
import Tests.TwoStepCounterSpec
import Tests.CreditsSpec
import Tests.WideSpec
import Tests.ConstSpec
import Tests.IdlSpec
import Tests.DumpIncrement
import Tests.NormalizationSpec
import Tests.SolanalibSpec
import Tests.TargetOpsSpec
import Tests.SvmHeapSpec
import Tests.SvmScratchSpec
import Tests.CFGSpec
import Tests.NestedSpec
import Tests.SeatSpec
import Tests.TreeSpec
import Tests.SvmSdkStorageSpec
import Tests.SvmSdkQueueSpec
import Tests.SvmSdkStorageBitSetSpec
import Tests.SvmSdkStorageEnumerableSetSpec
import Tests.SvmVersionedCodecSpec
import Tests.SvmSdkAccountSpec
import Tests.SvmTransientSpec
import Tests.SvmSdkPdaSystemSpec
import Tests.SvmSdkSystemSpec
import Tests.SvmSdkTokenSpec
import Tests.SvmSdkTokenStateSpec
import Tests.SvmSdkProgramSpec
import Tests.SvmSdkSysvarSpec
import Tests.EntryAdapterSpec
import Tests.AccountViewSpec
import Tests.SvmMemorySpec
import Tests.SvmAccountResizeSpec
import Tests.SvmTransientVectorSpec
import Tests.SvmTransientBytesSpec
import Tests.SvmTransientRecordSpec
import Tests.SvmTransientWideVectorSpec
import Tests.SvmWideReturnSpec
import Tests.SvmTelemetrySpec
import Tests.LamportTransferSpec
import Tests.SvmSdkPubkeySpec
import Tests.ProofSpec
