import ProofForge.Wasm.Host

/-!
# XRPL Bedrock host contract

XRPL Bedrock（XLS-0101）的宿主合同实例，注入家族共享发射器。拥有且仅拥有链间
必然不同的三件事：

1. **存储**：合约 pseudo-account 上的 `get_data` / `set_data`
   （`read_u64` / `write_u64` 助手，经 `get_current_contract_call()` 取账户）；
2. **host function**：v0 无（未来 capability 键钉在 `Xrpl.Ops`）；
3. **SDK / 入口 ABI**：`#[unsafe(no_mangle)] pub extern "C" fn … -> i32` 状态码 +
   取反 epilogue + `@xrpl-function` 注释；view `-> u64`。

编译面事实（来自旧仓 proof_forge 研究 ADR-0049/0050）：ambient
`cargo build --target wasm32-unknown-unknown --release` + `xrpl-wasm-std`
（git rev `ffbe88da26df27e59a72b6202883f42f696933cc`）；rustc/cargo 不是 Tool Lock；
XRPL 主网无 `ContractCreate`。
-/

namespace ProofForge.Wasm.Xrpl.Host

open ProofForge.Wasm.Host (Contract)

private def ob : String := "{"

private def indent (n : Nat) (s : String) : String :=
  String.ofList (List.replicate n ' ') ++ s

private def prelude : Array String := #[
  "#![cfg_attr(target_arch = \"wasm32\", no_std)]",
  "",
  "#[cfg(not(target_arch = \"wasm32\"))]",
  "extern crate std;",
  "",
  "use xrpl_wasm_std::core::current_tx::contract_call::get_current_contract_call;",
  "use xrpl_wasm_std::core::current_tx::traits::ContractCallFields;",
  "use xrpl_wasm_std::core::data::codec::{get_data, set_data};"
]

private def storageHelpers : Array String := #[
  "fn read_u64(key: &str) -> u64 {",
  "    let contract_call = get_current_contract_call();",
  "    let contract_account = contract_call.get_contract_account().unwrap();",
  "    match get_data::<u64>(&contract_account, key) {",
  "        Some(value) => value,",
  "        None => 0,",
  "    }",
  "}",
  "",
  "fn write_u64(key: &str, value: u64) -> Result<(), i32> {",
  "    let contract_call = get_current_contract_call();",
  "    let contract_account = contract_call.get_contract_account().unwrap();",
  "    set_data::<u64>(&contract_account, key, value)",
  "}"
]

/-- Entry wrapper for mutating entries: Bedrock status ABI. -/
private def wrapMutating (fnName params : String) (echoDropped : Bool)
    (loads body : Array String) : Array String := Id.run do
  let mut lines : Array String := #[s!"/// @xrpl-function {fnName}"]
  if echoDropped then
    lines := lines.push
      "/// v0 ABI: returns i32 status only; the public result value is elided (read via view)."
  lines := lines.push "#[unsafe(no_mangle)]"
  lines := lines.push s!"pub extern \"C\" fn {fnName}({params}) -> i32 {ob}"
  for load in loads do
    lines := lines.push load
  lines := lines.push (indent 4 "let result: Result<i32, i32> = (|| {")
  lines := lines ++ body
  lines := lines.push (indent 4 "})();")
  lines := lines.push (indent 4 "match result {")
  lines := lines.push (indent 8 "Ok(code) => code,")
  lines := lines.push (indent 8 "Err(code) => if code < 0 { code } else { -code },")
  lines := lines.push (indent 4 "}")
  lines := lines.push "}"
  return lines

/-- Entry wrapper for views: FFI-safe scalar return. -/
private def wrapView (fnName params : String) (loads body : Array String) :
    Array String := Id.run do
  let mut lines : Array String := #[s!"/// @xrpl-function {fnName}"]
  lines := lines.push "#[unsafe(no_mangle)]"
  lines := lines.push s!"pub extern \"C\" fn {fnName}({params}) -> u64 {ob}"
  for load in loads do
    lines := lines.push load
  lines := lines ++ body
  lines := lines.push "}"
  return lines

/-- The XRPL Bedrock host contract. -/
def contract : Contract where
  name := "xrpl"
  digestDomain := "xrpl-bedrock|"
  headerTag := "PROOF-FORGE-XRPL-BEDROCK v0"
  headerNotes := #[
    "// Generated by ProofForge. Target: XRPL Bedrock (XLS-0101) smart-features.",
    "// Source-shaped artifact: wrap in a cdylib crate and build with ambient",
    "// `cargo build --target wasm32-unknown-unknown --release` against xrpl-wasm-std",
    "// (git rev ffbe88da26df27e59a72b6202883f42f696933cc).",
    "// Honesty: zero-tool emission; deployable=false; no bedrock / rippled /",
    "// ContractCreate / ContractCall / AlphaNet / mainnet claim.",
    "// v0 ABI: views return u64; mutating entries return i32 status",
    "// (error codes: 1 overflow/underflow, 2 divide-by-zero)."
  ]
  prelude := prelude
  storageHelpers := storageHelpers
  readSlot := "read_u64"
  writeSlot := "write_u64"
  slotKey := fun name => s!"{name}_KEY"
  wrapMutating := wrapMutating
  wrapView := wrapView

end ProofForge.Wasm.Xrpl.Host
