import ProofForge.Wasm.Host

/-!
# XRPL Bedrock host contract

XLS-0102 wasm 级 ABI，注入家族共享 WAT 发射器：

- import 模块 `host_lib`
- 读：`get_current_ledger_obj_field(field, out_ptr, out_len) -> i32`
  （XLS-0102 草案名 `home_le_field`；Bedrock 本地镜像
  `lejamon/rippled_smart_contract_vault_x86` 仍注册旧名）
- 写：`update_data(data_ptr, data_len) -> i32`
  （草案名 `set_data`；同上，本地节点注册旧名）
- `Data` 的 sfield 是 `458779`（`0x0007001B`）

v0 把每个 UInt64 槽按声明顺序小端打包进这一份 Data blob。不是
`xrpl-wasm-std` 的 Rust 助手名（`get_data` / `get_current_contract_call`）。
XLS-0102 目前只钉 Smart Escrow host；同名函数将可从 smart contracts 访问。
v0 只用这一对存储调用。
-/

namespace ProofForge.Wasm.Xrpl.Host

open ProofForge.Wasm.Host (Contract)

/-- The XRPL Bedrock host contract. -/
def contract : Contract where
  name := "xrpl"
  digestDomain := "xrpl-bedrock|"
  headerTag := "PROOF-FORGE-XRPL-BEDROCK v0"
  headerNotes := #[
    ";; Generated by ProofForge. Target: XRPL Bedrock (XLS-0101).",
    ";; Artifact: WAT → wasm. Host: `host_lib` (Bedrock local ABI).",
    ";; Storage: get_current_ledger_obj_field / update_data, Data sfield 458779.",
    ";; Honesty: deployable=false on mainnet; no ContractCreate / AlphaNet claim.",
    ";; v0 ABI: views return i64; mutating entries return i32 status",
    ";; (error codes: 1 overflow/underflow, 2 divide-by-zero)."
  ]
  importModule := "host_lib"
  homeLeField := "get_current_ledger_obj_field"
  setData := "update_data"
  sfieldData := 458779

end ProofForge.Wasm.Xrpl.Host
