import ProofForge.Wasm.Host

/-!
# NEAR Protocol host contract

Historical proof_forge profile `near-wasm-raw-u64-v1` (docs/targets/03-near.md):

- import module `env` (NEAR runtime), not `host_lib` and not a generic `pf` module
- scalar params arrive as exactly `8 * paramCount` little-endian bytes via `env.input`
  (register 0); zero-arg methods require empty input; the bounded bytes/string extension uses
  canonical Borsh `u32_le(length) || active bytes`
- UInt64 slots persist as 8-byte little-endian values under ASCII field-name keys
  via `storage_read` / `storage_write`
- views and mutating public results `value_return` 8-byte LE; errors `panic_utf8`.
  This is **not** JSON ABI and **not** XRPL's C-param `i32`/`i64` export ABI.

The current profile uses this pair of storage calls plus `input` / `register_len` /
`read_register` / `value_return` / `panic_utf8`, context reads, and bounded static
`log_utf8`. Bounded bytes/string input is allocation-free; bounded output, promises, and
arbitrary storage stay fail closed.

The family `Wasm.Host.Contract` still describes XRPL's Data-blob import shape.
NEAR does not instantiate it; `Near.Emit` owns the env import table.
-/

namespace ProofForge.Wasm.Near.Host

def chainName : String := "near"

def digestDomain : String := "near-raw-u64|"

def headerTag : String := "PROOF-FORGE-NEAR-RAW-U64 v0"

def headerNotes : Array String := #[
  ";; Generated by ProofForge. Target: NEAR Protocol.",
  ";; Artifact: WAT → wasm. Host: `env` (near-wasm-raw-u64-v1).",
  ";; Storage: storage_read / storage_write, 8-byte LE per UInt64 slot.",
  ";; Input: raw-u64 or bounded Borsh bytes/String; views value_return 8-byte LE.",
  ";; Honesty: deployable=false; no nearcore / near-sandbox / testnet claim."
]

def importModule : String := "env"

end ProofForge.Wasm.Near.Host
